COVID_19_Tracker/urls.py
from django.urls import path

from . import views

app_name = "COVID-19"
urlpatterns = [
    path('',views.search_country,name="search_country"),
]

Covid19Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("COVID_19_Tracker.urls")),
]

COVID_19_Tracker/models.py
# Create your models here.
from django.db import models


class Global(models.Model):
    gid = models.CharField(max_length=100000,null=True,blank=True)
    newConfirmed = models.IntegerField()
    totalConfirmed = models.IntegerField()
    newDeaths = models.IntegerField()
    totalDeaths = models.IntegerField()
    newRecovered = models.IntegerField()
    totalRecoverd = models.BigIntegerField()
    update_date = models.DateTimeField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)



class Countries(models.Model):
    cid = models.CharField(max_length=10000, unique=True)
    country = models.CharField(max_length=1000)
    countryCode = models.CharField(max_length=100)
    slugId = models.SlugField()
    newConfirmed = models.IntegerField()
    totalConfirmed = models.IntegerField()
    newDeaths = models.IntegerField()
    totalDeaths = models.IntegerField()
    newRecovered = models.IntegerField()
    totalRecoverd = models.BigIntegerField()
    lat=models.DecimalField(max_digits=20,decimal_places=10,blank=True,null=True)
    lon=models.DecimalField(max_digits=20,decimal_places=10,blank=True,null=True)
    date = models.DateTimeField()

    def __str__(self):
        return self.country


class CountriesHistory(models.Model):
    cid = models.CharField(max_length=10000, unique=True)
    country = models.CharField(max_length=1000)
    countryCode = models.CharField(max_length=100)
    slugId = models.SlugField()
    newConfirmed = models.IntegerField()
    totalConfirmed = models.IntegerField()
    newDeaths = models.IntegerField()
    totalDeaths = models.IntegerField()
    newRecovered = models.IntegerField()
    totalRecoverd = models.BigIntegerField()
    date = models.DateTimeField()
    saved_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.date)


class India(models.Model):
    state=models.CharField(max_length=1000)
    state_code = models.CharField(max_length=100)
    active = models.BigIntegerField()
    confirmed = models.BigIntegerField()
    deaths = models.BigIntegerField()
    recovered = models.BigIntegerField()
    new_confirmed = models.BigIntegerField()
    new_deaths = models.BigIntegerField()
    new_recovered = models.BigIntegerField()
    last_update_time = models.DateTimeField()
    lat = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    lon = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)


class IndiaHistory(models.Model):
    state = models.CharField(max_length=1000)
    state_code = models.CharField(max_length=100)
    active = models.BigIntegerField()
    confirmed = models.BigIntegerField()
    deaths = models.BigIntegerField()
    recovered = models.BigIntegerField()
    new_confirmed = models.BigIntegerField()
    new_deaths = models.BigIntegerField()
    new_recovered = models.BigIntegerField()
    last_update_time = models.DateTimeField()
    creation_date = models.DateTimeField(auto_now_add=True)

class CountryCode(models.Model):
    iso=models.CharField(max_length=128)
    name=models.CharField(max_length=1000)

COVID_19_Tracker/forms.py
from django import forms
from .models import India


class IndiaForm(forms.ModelForm):
    class Mata:
        model = India
        fields = "__all__"



class SearchLocation(forms.Form):
    location_name = forms.CharField(max_length=1000,
                                    widget=forms.TextInput(attrs={'class': 'form-control bg-light border-0 search sm-search',
                                                                  'data-toggle': 'popover',
                                                                  'title': '',
                                                                  'data-content': "Default Value",
                                                                  # 'data-trigger':'focus',
                                                                  'data-placement': 'bottom',
                                                                  'data-html': "true",
                                                                  'placeholer':'type Country name',
                                                                  }))

COVID_19_Tracker/views.py
from math import sqrt

import folium
from django.shortcuts import render
from geopy.geocoders import Nominatim

from .forms import SearchLocation
from .models import Global, Countries, India


# App View
def search_country(request):
    geolocators = Nominatim(user_agent="COVID_19_Tracker")      # Initialize App folder to get latitude and longitude
    country = indiadata = total = country_all = tooltip_text = data = map = None    # Initialize context variables
    country_name_list = Countries.objects.values_list('country', flat=True)     # Fetched all country name as a list
    if request.method == "POST":            # When user search country or state or district
        searchform = SearchLocation(request.POST)
        if searchform.is_valid():       # Checking the user input value is empty or not
            pk = searchform.cleaned_data['location_name']       # Getting user input and store in a variable

            if pk.upper() == "INDIA":
                indiadata = India.objects.exclude(state_code="TT")  # Getting all rows of India table except (Total) row
                total = India.objects.get(state_code="TT")  # Getting (Total Cases) row
                indialoc = geolocators.geocode(pk)      # Getting India's Latitude Longitude
                map = folium.Map(location=(indialoc.latitude, indialoc.longitude), zoom_start=4.5)  # Creating a Map to specific loation
                for i in indiadata:
                    statelocation = (i.lat, i.lon)      # Getting each state location's latitude longitude
                    tooltip_text = f"{i.state.capitalize()}<br>" \
                                   f"Confirmed: {i.confirmed}<br>" \
                                   f"Recovered: {i.recovered}"
                    rad = sqrt(i.confirmed) / 20        # Fixed radius of India view on Map

                    folium.CircleMarker(location=statelocation, radius=rad, tooltip=tooltip_text, fill=True,
                                        fill_color="#428bca").add_to(map)   # Draw circle's of each location's, added to Map object
            else:
                country = Countries.objects.get(country__iexact=pk)  # Different Country Details
                location = (country.lat, country.lon)

                map = folium.Map(location=location, min_zoom=2, zoom_start=5)
                country_all = Countries.objects.all()  # context

                for i in country_all:
                    pk = i.slugId
                    if i.lat is None:
                        continue

                    else:
                        location = (i.lat, i.lon)
                        rad = sqrt(i.totalConfirmed) / 100 + 3
                        tooltip_text = f"{str(pk).capitalize()}<br>" \
                                       f"Confirmed: {i.totalConfirmed}<br>" \
                                       f"Recovered: {i.totalRecoverd}"
                        folium.CircleMarker(location=location, radius=rad, tooltip=tooltip_text, fill=True,
                                            fill_color="#428bca").add_to(map)

    else:  # Get request when page loaded Global
        searchform = SearchLocation()  # context

        map = folium.Map(min_zoom=1.5)  # fetch live location  context
        country_all = Countries.objects.all()  # context
        data = Global.objects.last()  # context

        for i in country_all:
            pk = i.slugId
            if i.lat is None:
                continue
            else:
                location = (i.lat, i.lon)
                rad = sqrt(i.totalConfirmed) / 100 + 3
                tooltip_text = f"{pk}<br>" \
                               f"Confirmed: {i.totalConfirmed}<br>" \
                               f"Recovered: {i.totalRecoverd}"
                folium.CircleMarker(location=location, radius=rad, tooltip=tooltip_text, color="#428bca", fill=True,
                                    fill_color="#428bca").add_to(map)

    map = map._repr_html_()
    context = {'country': country,
               'indiadata': indiadata,
               'total': total,
               'map': map,
               'searchform': searchform,
               'country_all': country_all,
               'country_name_list': country_name_list,
               }
    if data:
        context.update({'country': data})
        context.update({'global': True})

    return render(request, 'covid/CountryDetails.html', context)


def search_state(request):
    pass

COVID_19_Tracker/templates/covid/CountryDetails.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block title %} {% if total %} India {% elif global %}Global {% else %}{{country.country}} {% endif %} {% endblock %}
{% block css %}
<link href="{% static 'covid/css/indiadata.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
{% include 'covid/navbar.html' %}
<div class="container-fluid">
    <div class="row d-md-none">
        <div class="col">
            <p class="h2 alert-danger text-danger w-50 text-center rounded pt-1 pb-1">
                {% if global %}
                Global
                {% elif total %}
                India
                {% else %}
                {{country.country|capfirst}}
                {% endif %}
            </p>
        </div>
    </div>
    <div class="row d-md-none mb-5">
        <div class="col">
            {% if total %}
            <small class="text-muted">Last Update on {{total.last_update_time|date:"d M Y , h:i A"}}
                ({{total.last_update_time|naturaltime}})</small>
            {% else %}
            <small class="text-muted">Last Update on {{country.date|date:"d M Y , h:i A"}}
                ({{country.date|naturaltime}})</small>
            {% endif %}
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col">
            {% if total %}
            <div class="row d-none d-sm-flex">
                <p class="offset-4 text-muted">Search your disctrict or state</p>
                <span class="offset-6 mb-1 search-upper d-none d-sm-inline-block"></span>
                    <div class="input-group mb-3 shadow mb-5 p-2 ml-4 mr-4 rounded dataTables_filter">
                        <input area-controls="table_id" aria-describedby="table_id_info"
                               class="form-control border-0 search" placeholder="Type state or district name" type="search">
                        <div class="input-group-append">
                            <button class="btn border-0" type="submit"><i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
            </div>
            {% endif %}
            <div class="row">
                {% if total %}
                {% include 'covid/IndiaData.html' %}
                {% else %}

                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col mb-4">
                    <!--    Card Area    -->
                    <div class="card alert-danger border-0 w-100">
                        <div class="card-body">
                            <h5 class="card-title h3">Confirmed</h5>
                            <small class="text-muted counterUp today">
                                {{country.newConfirmed}}
                            </small>
                            <p class="card-text h3">
                                {{country.totalConfirmed|intword|slice:":7"|upper}}
                            </p>

                        </div>
                    </div>
                    <!--    End - card Area  -->
                </div>
                {% if country.active %}
                <div class="col-xl-3 col-lg-4 col-md-4 col-sm-6 col ">
                    <!--    Card Area    -->
                    <div class="card alert-primary border-0 w-100">
                        <div class="card-body">
                            <h5 class="card-title h3">Active</h5>
                            <small class="text-muted counterUp today">{{total.active}}</small>
                            <p class="card-text counterUp h3">
                                {{total.active|intword}}
                            </p>
                        </div>
                    </div>
                    <!--    End - card Area  -->
                </div>
                {% endif %}

                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col mb-4">
                    <!--    Card Area    -->
                    <div class="card alert-success border-0 w-100">
                        <div class="card-body">
                            <h5 class="card-title h3">Recovered</h5>
                            <small class="text-muted counterUp today">{{country.newRecovered}}</small>
                            <p class="card-text h3">
                                {{country.totalRecoverd|intword|slice:":6"|upper}}
                            </p>
                        </div>
                    </div>
                    <!--    End - card Area  -->
                </div>

                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col">
                    <!--    Card Area    -->
                    <div class="card alert-secondary border-0 w-100">
                        <div class="card-body">
                            <h5 class="card-title h3">Deaths</h5>
                            <small class="text-muted counterUp today">{{country.newDeaths}}</small>
                            <p class="card-text  h3">
                                {{country.totalDeaths|intword|slice:":5"|upper}}
                            </p>
                        </div>
                    </div>
                    <!--    End - card Area  -->
                </div>
                {% endif %}
            </div>


        </div>
        <div class="mt-5 col-xl-6 col-lg-6 col-md-6 col-sm-12">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col">
                    <div class="row d-none d-md-block">
                        <div class="col">
                            <p class="h2 alert-danger text-danger w-50 text-center rounded pt-1 pb-1">
                                {% if global %}
                                Global
                                {% elif total %}
                                India
                                {% else %}
                                {{country.country|capfirst}}
                                {% endif %}
                            </p>
                        </div>
                    </div>
                    <div class="row d-none d-md-block">
                        <div class="col">
                            {% if total %}
                            <small class="text-muted">Last Update on {{total.last_update_time|date:"d M Y , h:i A"}}
                                ({{total.last_update_time|naturaltime}})</small>
                            {% else %}
                            <small class="text-muted">Last Update on {{country.date|date:"d M Y , h:i A"}}
                                ({{country.date|naturaltime}})</small>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {{map|safe}}
                </div>

            </div>
        </div>
    </div>
    <!--     Data table show with in the gap       -->

    <div class="row mt-5">
        {% if total %}
        <div class="col-xl-12 col-lg-12 col-md-12">
            {% if total %}
            <div class="row  d-sm-none">
                <p class="offset-4 text-muted">Search your disctrict or state</p>
                <span class="offset-6 mb-1 search-upper d-none d-sm-inline-block"></span>
                    <div class="input-group mb-3 shadow mb-5 p-2 ml-4 mr-4 rounded dataTables_filter">
                        <input area-controls="table_id" aria-describedby="table_id_info"
                               class="form-control border-0 search" placeholder="Type state or district name" type="search">
                        <div class="input-group-append">
                            <button class="btn border-0" type="submit"><i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
            </div>
            {% endif %}
            <div class="container shadow p-4  bg-white shadow-box table-Data">
                <table class="display table table-hover" id="table_id">
                    <thead>
                    <tr class="bg-primary text-white">
                        <th>State</th>
                        <th>Total Confirmed</th>
                        <th>Total Deaths</th>
                        <th>Total Recoverd</th>
                        <th>Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for India_Data in indiadata %}
                    {% if India_Data.state == "" %}
                    {% comment %} not show{% endcomment %}
                    {% else %}
                    <tr>

                        <td>{{India_Data.state}}</td>
                        <td>{{India_Data.confirmed}}</td>
                        <td>{{India_Data.deaths}}</td>
                        <td>{{India_Data.recovered}}</td>
                        <td>{{India_Data.last_update_time|date:"d M Y"}}</td>

                    </tr>
                    {% endif %}
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            <!-- End of the Table Data -->
        </div>
        {% elif global %}
        {% include 'covid/TableData.html' %}
        {% else %}
        <p class="text-secondary ml-5">Sorry the table only available for India and Global only</p>
        {% endif %}
    </div>

</div>
{% endblock %}

{% block js %}
<script src="{% static 'covid/js/country.js' %}"></script>
<script>
    $(document).ready(function(){

        let listArr=[];
        var c=0;
       {% for i in country_name_list %}
            listArr[c] = "{{i}}";
            c++;
     {% endfor %}
     var country_list_str="";
     for( let j=0;j<listArr.length;j++)
     {
        country_list_str+="<p class='country_list text-muted'>"+listArr[j]+"</p>";
      }


      $("[data-toggle='popover']").popover();
     $("[data-toggle='popover']").attr('data-content',country_list_str);
     $('.form-control').click(function(){
        $('.popover').addClass('overflow-hidden h-25 w-100');
     });
     $('.form-control').keyup(function(){
        var data=$('.form-control').val().toUpperCase();
        if(data != '')
        {
            let x=document.getElementsByClassName("country_list");
            for(var i=0;i<x.length;i++)
            {
                let name=x[i].textContent.toUpperCase();
                if(name.indexOf(data) > -1){
                x[i].style.display="";
                }
                else{
                x[i].style.display="none";
                }
            }
        }
     });
    });
</script>
{% endblock %}

COVID_19_Tracker/templates/covid/IndiaData.html
{% load humanize %}
<div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col mb-4">
    <!--    Card Area    -->
    <div class="card alert-danger border-0 w-100">
        <div class="card-body">
            <h5 class="card-title">Confirmed</h5>
            <small class="text-muted today counterUp">+{{total.new_confirmed}}</small>
            <p class="card-text h3">
                {{total.confirmed|intword|slice:":6"|upper}}
            </p>
        </div>
    </div>
    <!--    End - card Area  -->
</div>
<div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col mb-4 ">
    <!--    Card Area    -->
    <div class="card alert-primary border-0 w-100">
        <div class="card-body">
            <h5 class="card-title">Active</h5>
            <small class="text-muted today counterUp">+{{total.active}}</small>
            <p class="card-text counterUp h3">
                {{total.active|intword}}
            </p>
        </div>
    </div>
    <!--    End - card Area  -->
</div>

<div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col mb-4">
    <!--    Card Area    -->
    <div class="card alert-success border-0 w-100">
        <div class="card-body">
            <h5 class="card-title">Recovered</h5>
            <small class="text-muted today counterUp">+{{total.new_recovered}}</small>
            <p class="card-text h3">
                {{total.recovered|intword|slice:":6"|upper}}
            </p>
        </div>
    </div>
    <!--    End - card Area  -->
</div>

<div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col mb-4">
    <!--    Card Area    -->
    <div class="card alert-secondary border-0 w-100">
        <div class="card-body">
            <h5 class="card-title">Deaths</h5>
            <small class="text-muted today counterUp">+{{total.new_deaths}}</small>
            <p class="card-text counterUp h3">
                {{total.deaths|intword|slice:":6"|upper}}
            </p>
        </div>
    </div>
    <!--    End - card Area  -->
</div>

COVID_19_Tracker/templates/covid/TableData.html
{% load humanize %}
<div class="container border p-4 bg-white shadow-box table-Data w-100">
    <table class="display responsive table table-hover stripe row-border order-column wrap w-100" id="table_id">
        <thead>
        <tr class="bg-primary text-white">
            <th>Country</th>
            <th>New Confirmed</th>
            <th>Total Confirmed</th>
            <th>New Deaths</th>
            <th>Total Deaths</th>
            <th>New Recovered</th>
            <th>Total Recoverd</th>
        </tr>
        </thead>
        <tbody>
        {% for country_Data in country_all %}
        <tr>
            <td>{{country_Data.country}}</td>
            <td>{{country_Data.newConfirmed}}</td>
            <td>{{country_Data.totalConfirmed}}</td>
            <td>{{country_Data.newDeaths}}</td>
            <td>{{country_Data.totalDeaths}}</td>
            <td>{{country_Data.newRecovered}}</td>
            <td>{{country_Data.totalRecoverd}}</td>
        </tr>
        {% endfor %}

        </tbody>
    </table>
</div>
<!-- End of the Table Data -->

COVID_19_Tracker/templates/covid/navbar.html
<div class="container-fluid bg-white mb-5 pb-2 pt-2 shadow sticky-top top-fixed">
    <nav class="navbar navbar-expand-md navbar-light bg-white ">
        <a class="navbar-brand" href="{% url 'COVID-19:search_country' %}">COVID-19</a>
        <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-4">
                <li class="nav-item active ml-4">
                    <a class="nav-link" href="{% url 'COVID-19:search_country' %}">Home <span
                            class="sr-only">(current)</span></a>
                </li>

                <form action="{% url 'COVID-19:search_country' %}" method="POST" autocomplete="off">
                    {% csrf_token %}
                    <div class="input-group  ml-4 mr-4 rounded">

                        {% for form in searchform %}
                        {{form}}
                        {% endfor %}
                        <div class="input-group-prepend">
                            <button class="btn border-0" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                    <div id="list_search" class="d-none d-sm-none">
                    </div>
                </form>

                <li class="nav-item ml-4">
                    <a class="nav-link" href="#">Statistics</a>
                </li>
            </ul>
        </div>
    </nav>
</div>